apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-task-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sherifa1913/devops-task-manager.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: taskmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
